apiVersion: apps/v1
kind: Deployment
metadata: 
  name: dbis-storage-service
  labels:
    app: dbis-storage-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: dbis-storage-service
  template:
    metadata:
      labels:
        app: dbis-storage-service
    spec:
      containers:
        - name: dbis-storage-service-container
          image: andriideveloper/dbis-storage-service
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: PORT
              valueFrom:
                configMapKeyRef:
                  name: dbis-storage-service-config
                  key: port
            - name: HOST
              valueFrom:
                configMapKeyRef:
                  name: dbis-storage-service-config
                  key: host
            - name: GOOGLE_CLOUD_PROJECT_ID
              valueFrom:
                secretKeyRef:
                  name: dbis-storage-service-secret
                  key: google-cloud-project-id
            - name: GOOGLE_CLOUD_SECRET_FILE_NAME
              valueFrom:
                secretKeyRef:
                  name: dbis-storage-service-secret
                  key: google-cloud-secret-file
            - name: MATERIALS_BUCKET_NAME
              valueFrom:
                secretKeyRef:
                  name: dbis-storage-service-secret
                  key: material-bucket-name
            - name: GOOGLE_STORAGE_LINK
              valueFrom:
                secretKeyRef:
                  name: dbis-storage-service-secret
                  key: google-storage-link
            - name: MONGO_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: dbis-storage-service-secret
                  key: mongo-connection
---
apiVersion: v1
kind: Service
metadata:
  name: dbis-storage-service-loadbalancer
spec:
  selector:
    app: dbis-storage-service
  ports:
    - name      : api-listener
      protocol  : TCP
      port      : 80
      targetPort: 5000
  type: LoadBalancer
