version: '3'

services:
  mongo: 
    image: mongo:4.0-xenial
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: $MONGO_ADMIN_USERNAME
      MONGO_INITDB_ROOT_PASSWORD: $MONGO_ADMIN_PASS
      MONGO_USER: $MONGO_USER
      MONGO_PASS: $MONGO_PASS
      MONGO_DB: $MONGO_DB
      MONGO_INITDB_DATABASE: $MONGO_DB 
    ports:
      - 3000:27017
    volumes:
      - ./db-data:/data/db
      - ./init-mongo.sh:/docker-entrypoint-initdb.d/init-mongo.sh:ro

  app:
    build: .
    env_file:
      - .env.production
    environment: 
      - NODE_ENV=production
    ports: 
      - 5000:5000

volumes:
  db-data:
