require('dotenv').config()

module.exports = {
  GOOGLE_CLOUD_PROJECT_ID: process.env.GOOGLE_CLOUD_PROJECT_ID,
  MATERIALS_BUCKET_NAME: process.env.MATERIALS_BUCKET_NAME,
  GOOGLE_CLOUD_SECRET_FILE_NAME: process.env.GOOGLE_CLOUD_SECRET_FILE_NAME,
  GOOGLE_STORAGE_LINK: process.env.GOOGLE_STORAGE_LINK
};
